### ISSUE TITLE
AWS error when running script after auto logon

### ISSUE THREAD

**Issue by mukreb** [parsec-cloud/Parsec-Cloud-Preparation-Tool#41] opened 2020-06-09 17:49 UTC
When running the script on AWS following the instructions on https://www.richardneililagan.com/posts/create-game-server-aws-parsec I ran (twice) into this error after saying Y on Auto Login configuration. Not sure if its a bad thing, everything seems to work after this:

```
Method invocation failed because [System.Boolean] does not contain a method named 'trim'.
At C:\Users\Administrator\Desktop\parsectemp\PostInstall\PostInstall.ps1:394 char:1
+ [int]$i = $gpoversion.trim("Version=")
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [System.Boolean] does not contain a method named 'trim'.
At C:\Users\Administrator\Desktop\parsectemp\PostInstall\PostInstall.ps1:395 char:1
+ [int]$n = $gpoversion.trim("Version=")
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
```

**Comment by jamesstringerparsec** [comment] 2020-12-22 11:15
I'm wondering if;

a) you either used Powershell 7 when running this script
b) the machine already had GPOs set when you ran this script

It's been months since you've made this issue however so you may have forgotten.

**Comment by mukreb** [comment] 2020-12-22 11:25
Thanks for replying! I dont have this setup running anymore so unfortunately I can't look it up anymore :-(

**Comment by jamesstringerparsec** [comment] 2020-12-22 11:26
In that case I will close it since no one recently has experienced this issue

**Closed by jamesstringerparsec** 2020-12-22 11:26 UTC

**Comment by r-ichard** [comment] 2020-12-27 10:30
Hello ! I had the same issue. 
I followed the same tutorial as @mukreb 

I checked powershell version using `Get-Host | Select-Object Version` 
And I got "5.1.17763.1490"  

Anyway parsec still launched but I have no "Auto Logon"  on my desktop. Is this normal ? How can I check if everything is installed correctly ?

**Comment by jamesstringerparsec** [comment] 2020-12-27 10:45
For your information, the guide you are referring to is not mine and is out of date.

Given that both of you experience this issue while using the guide, but no one else reports the issue who doesn't use the guide...I'm guessing something inside the guide is causing the issue.

Please try set up the instance without following the guide and if the issue persists, let me know.

**Comment by jamesstringerparsec** [comment] 2020-12-27 10:50
The Part of the guide that you are using that is causing the issue is most likely below, which is not actually required and should be ignored.

```Disable CTRL+ALT+DELETE to unlock

By default, Windows is set up to require you to press CTRL+ALT+DELETE whenever you unlock the machine --- once Parsec is set up (and we’re not using RDP anymore), we won’t be able to do that, so we’ll need to disable this (so that Parsec can also autologin for us).

From your Start Menu, search for Local Security Policy. Navigate to Local Policies > Security Options, and change the Interactive Logon: Do not require CTRL + ALT + DEL option to Enable.
```

**Comment by r-ichard** [comment] 2020-12-27 17:38
Ok thank you very much !

 Can I run the script again to be sure that everything went correctly or will it fail  or break something ?

**Comment by jamesstringerparsec** [comment] 2020-12-28 11:35
You should create a new instance, and skip the CTRL + ALT + DELETE that is listed in that guide.  Just note that guide isn't created by someone who works for Parsec and is outdated.  You no longer see an AUTOLOGIN method on the desktop, you do that within the script now.
