### ISSUE TITLE
GPU Update fails to update NVIDIA Driver

### ISSUE THREAD

**Issue by sabatale** [parsec-cloud/Parsec-Cloud-Preparation-Tool#48] opened 2020-11-01 19:05 UTC
**ENVIRONMENT**
Google Cloud GPU NIVIDIA P4 (Virtual Workstation) WIN 2019.

**ISSUE**
After running the Cloud Preparation Tool on a fresh instance (no issues), I'm trying to run the GPU Update with Admin rights.

The tool detects the current driver version as well as the latest available. It is downloaded, installed, etc. without error messages.

However, when checking the new driver version, I can see it hasn't actually been updated. I'm wondering if there is a log of what is happening within the GPU Update and why it is not getting updated?

PS. Installing any driver from Google Storage manually is working fine: [https://cloud.google.com/compute/docs/gpus/grid-drivers-table](https://cloud.google.com/compute/docs/gpus/grid-drivers-table)

**Comment by jamesstringerparsec** [comment] 2020-12-27 15:55
I have recently launched both T4 and P4 instances with Google cloud and experienced no issues installing the driver using the tool.  Closing as unable to reproduce.

**Closed by jamesstringerparsec** 2020-12-27 15:55 UTC
